/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[252] =
    {   0,
       19,   19,   65,   64,    1,   64,   33,   64,   60,   64,
       64,   23,   64,   30,   64,   64,   36,   64,   37,   64,
       22,   64,   42,   64,   22,   64,   55,   62,   64,   23,
       64,   18,   19,   64,   43,   64,   25,   64,   26,   64,
       25,   64,   44,   64,   44,   64,   40,   64,   41,   64,
       30,   64,   44,   64,   44,   64,   44,   64,   44,   64,
       44,   64,   44,   64,   44,   64,   44,   64,   44,   64,
       44,   64,   44,   64,   44,   64,   38,   64,   30,   64,
       39,   64,   25,   60,   60,   46,   60,   27,   63,   59,
       24,   55,   19,   55,   61,   47,   59,   55,   18,   19,

       57,   57,   57,   30,   44,   56,   19,   44,   44,   44,
       44,   44,   44,   44,    6,   44,   44,   44,   44,   44,
        2,   44,   44,   44,   44,   44,   44,   60,   45,   46,
       20,   55,   61,   61,   54,   47,   47,   47,   47,   55,
       57,   57,   19,   57,   57,   57,   19,   56,   44,   44,
       44,   44,   44,   44,   44,   44,    4,   44,   44,    8,
       44,   44,   44,   44,   44,   58,   21,   61,   48,   61,
       47,   54,   47,   44,   15,   44,    9,   44,   44,   44,
       44,    3,   44,   44,   44,   44,   44,   12,   44,   44,
       61,   48,   61,   47,   47,    7,   44,   44,   44,   44,

       10,   44,   44,   44,   44,    5,   44,   61,   44,   44,
       11,   44,   44,   13,   44,   14,   44,   48,   44,   16,
       44,   44,   17,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   53,   44,   44,   50,   50,   49,   51,   51,
       44,   44,   52,   44,   44,   34,   31,   28,   35,   32,
       29
    } ;

static yyconst short int yy_accept[414] =
    {   0,
        1,    2,    3,    3,    3,    4,    5,    7,    9,   11,
       12,   14,   16,   17,   19,   21,   23,   25,   27,   30,
       32,   35,   37,   39,   41,   43,   45,   47,   49,   51,
       53,   55,   57,   59,   61,   63,   65,   67,   69,   71,
       73,   75,   77,   79,   81,   83,   84,   85,   86,   87,
       88,   88,   89,   89,   90,   91,   91,   92,   93,   95,
       96,   96,   97,   97,   98,   99,  101,  102,  103,  104,
      105,  106,  106,  107,  109,  110,  111,  112,  113,  114,
      115,  117,  118,  119,  120,  121,  123,  124,  125,  126,
      127,  128,  129,  131,  131,  131,  131,  132,  132,  132,

      133,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  157,  159,  160,  162,  163,  164,
      165,  166,  166,  167,  168,  169,  171,  173,  174,  175,
      177,  179,  180,  181,  182,  184,  185,  186,  187,  188,
      190,  191,  191,  192,  194,  195,  196,  198,  199,  200,
      201,  203,  204,  205,  206,  208,  208,  209,  210,  211,
      213,  214,  216,  218,  218,  219,  220,  222,  223,  223,
      225,  226,  227,  227,  228,  229,  229,  229,  230,  231,
      231,  231,  231,  232,  233,  233,  233,  234,  234,  234,

      234,  235,  236,  237,  238,  240,  240,  241,  242,  243,
      244,  244,  245,  245,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  247,  247,
      247,  247,  247,  247,  247,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  250,  250,  250,  251,  251,
      251,  252,  252
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   25,   28,   25,
       29,   25,   30,   25,   31,   32,   25,   33,   34,   35,
       25,   25,   25,   36,   25,   25,   25,   25,   25,   25,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   51,   58,   59,   60,   61,   62,   63,   64,
       65,   51,   66,   67,   68,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    5,    1,
        1,    6,    1,    1,    1,    7,    8,    9,   10,    1,
        1,    1,    1,    1,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    1,    4,    1,    1,
       12,    9,    9,   10,   10,   10,    9,   10,   10,   10,
       10,   10,   10,   10,    9,   10,   10,    9,   10,    9,
       10,    9,   10,   10,   10,    1,    1,    1
    } ;

static yyconst short int yy_base[429] =
    {   0,
        0,    0,    0,    0, 1058, 1059, 1059, 1034,   68, 1006,
     1059, 1047,  136, 1059, 1059, 1041, 1059, 1038,  189,  194,
      203, 1059,  191, 1029,  192, 1042,  260, 1059, 1059, 1059,
      264,  292,  992,  228,  171,  996,  229,  171, 1002,  984,
      990,  996, 1059,  977, 1059, 1059,  171, 1038,  236,  238,
      987, 1059, 1032, 1031, 1030, 1029, 1059,  286,  313, 1025,
      287,  341,  271, 1059,  319, 1027,  205,  297,  394, 1059,
     1026,  398,  253,  422, 1025,  406,  409,  297,  233,  423,
      424,  425,  426,  428,  430, 1024,  427,  433,  439,  440,
      441,  441,  302,  439,  454,  988, 1059, 1022, 1021,  435,

      442, 1017,  450, 1059,  478,  447,    0, 1026,  456,  315,
      446,  482,  528,    0,  486,  488,  436,  457,  460,  490,
      467,  438,  464,  474, 1018,  499, 1017,  504,  506,  503,
      542,  972, 1059, 1059,  555, 1012,    0,  985,  559, 1013,
     1012,  502,  508,  561, 1011,  562,  564,  565,  566, 1010,
      567,  957, 1005, 1004,  977,  577, 1005,  569,  568,  571,
     1004,  572,  573,  576, 1003,  966,  571,  575,  577, 1001,
      580, 1000,  999,  961, 1059,  583,  997,  578,  983,  995,
      584,  585,  617,  582,  581,  638,  987,  599,  588,  659,
      978,  586,  595,  603,  977,  660,  976,  577,  661,  975,

      597,  630, 1059,  974, 1059,  654, 1059,  589,  598, 1059,
      965,  600,  946,  591,  940,  972,  947,  656,  989,  961,
      956,  955,  933,  951,  957,  949,  928,  949,  952,  967,
      977,  944,  951,  970,  969,  961,  940,  914,  927,  964,
      935,  945,  948,  908,  952,  951,  961,  939,  955,  896,
      924,  945,  899,  892,  922,  890,  930,  893,  921,  886,
      936,  903,  920,  887,  881,  881,  911,  897,  877,  881,
      937,  875,  878,  916,  914,  875,  888, 1059,  664,  912,
      868,  901,  896,  895, 1059,  868,  891,  897,  889,  903,
      889,  892,  897, 1059,  885,  892,  915,  893,  882,  883,

      911,  878,  866,  879,  886,  845,  862,  904,  860,  841,
      872,  849,  856,  855,  854,  845,  834,  894,  850,  849,
      887,  890,  838,  832,  883,  843,  885,  828,  883,  838,
      881,  876,  826,  834,  821,  818,  822,  874,  821,  814,
      827,  828,  817,  815,  868,  824,  807,  853,  864,  810,
      811,  849,  817,  811,  807,  857,  803,  807,  842,  809,
      799,  800,  811,  772,  731,  736,  738,  718,  716,  727,
      723,  696,  689,  692,  677,  670,  684,  647,  651,  649,
      690,  642,  640,  635,  685,  643,  630,  629,  633,  632,
      626,  667,  634,  619,  597,  597,  574,  553,  556,  535,

      536,  493,  276,  284, 1059,  293,  161, 1059,   78,   49,
     1059, 1059,  710,  717,  725,  731,  743,  755,  765,  773,
      782,  786,  792,  804,  816,  821,  827,  839
    } ;

static yyconst short int yy_def[429] =
    {   0,
      412,    1,  413,  413,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  414,
      412,  412,  412,  412,  412,  415,  415,  412,  412,  412,
      416,  416,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,  412,  412,  412,  412,  417,    9,  418,    9,
      412,  412,  412,  412,  419,  420,  412,  412,  412,  421,
      412,  412,  414,  412,  412,   21,  422,  422,  423,  412,
      415,  412,  412,  415,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,  417,  418,  418,  418,  412,  412,  419,  412,  412,

      412,  421,  421,  412,   62,  105,   62,  105,  412,  422,
      422,  422,  423,  113,  412,  412,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,  412,  412,  412,  424,  421,  105,  425,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,  412,  424,  424,  425,  425,   32,   32,   32,   32,
       32,   32,   32,   32,   32,  412,  412,   32,   32,   32,
       32,   32,   32,  412,  412,   32,   32,   32,  412,   32,
       32,   32,  426,   32,   32,  426,  427,   32,   32,  428,
      186,  428,   32,   32,  412,  428,  412,  412,  428,  412,

       32,   32,  412,  412,  412,  412,  412,   32,   32,  412,
      412,   32,  412,   32,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,    0,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412
    } ;

static yyconst short int yy_nxt[1128] =
    {   0,
        6,    7,    6,    8,    9,   10,   11,   12,   13,   14,
       15,   11,   16,   17,   18,   19,   20,   21,   21,    6,
       22,   23,   24,   25,   26,   26,   26,   27,   26,   26,
       26,   26,   26,   26,   26,   26,   28,    6,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   32,   32,   38,
       32,   32,   32,   32,   32,   32,   32,   39,   40,   32,
       32,   41,   42,   32,   32,   43,   44,   45,   47,  411,
       48,   47,   49,   47,   47,   47,   48,   47,   47,   47,
       47,   47,   47,   47,   47,   48,   48,   47,   47,   47,
       47,   47,   48,   48,   48,   48,   48,   48,   48,   48,

       48,   48,   48,   48,   47,   50,   47,   47,   47,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   47,   47,   47,   53,  410,   53,   53,
       53,   53,   53,   53,   54,   53,   53,   53,   53,   53,
       53,   53,   53,   55,   55,   53,   53,   53,   53,   53,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   53,   56,   53,   49,   53,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   53,   53,   53,   58,   60,   59,   59,   92,   61,
       62,   64,   70,   46,   46,   70,   80,   86,   65,   63,
       66,   66,  110,  110,  409,   87,   81,   67,   67,   67,
       68,   67,   67,   67,   67,   67,   67,   67,   67,   47,
       49,  412,   93,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   64,   77,
      116,  116,   72,   95,   72,   73,   78,   74,   74,   61,
       63,   83,  412,   79,   84,   85,   61,  120,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       64,   58,   61,  100,  100,  412,   49,   61,   63,   72,
      104,   72,   73,  408,  112,  112,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   58,  407,
       59,   59,  110,  110,  109,  406,   59,   59,  119,   95,
      101,  105,  104,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  106,  107,  107,  107,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  108,  105,
      105,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  105,  105,  105,   61,
       63,  113,  113,   73,  412,  115,  115,  412,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      412,  412,  412,  412,  412,  412,  412,   73,  412,   74,
       74,  412,   47,   49,  412,   49,  412,  412,  412,  412,
       58,  117,  100,  100,   72,   94,   72,   73,   49,  115,
      115,  103,  106,  110,  110,  412,  136,  118,  412,  121,
      137,  109,  412,  100,  100,  412,   95,  139,   92,  104,
      144,  124,  412,  123,  122,  125,  127,  126,  129,  130,
      131,   95,  128,  105,  105,  105,  105,   73,  412,  112,

      112,   73,  140,  115,  115,  116,  116,  412,  143,  145,
      412,  412,  412,  405,  412,  146,  412,  141,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,   61,   63,  113,  113,  150,  147,  142,
      412,  158,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  148,  149,  135,  412,  159,  412,
      412,  154,  412,  412,  412,  412,  412,  412,  138,  412,
      412,  412,  167,  412,  412,  412,  412,  175,  412,  412,
      412,  412,  412,  412,  151,  404,  412,  412,  403,  412,

      205,  199,  211,  412,  216,  412,  412,  412,  412,  164,
      157,  412,  165,  160,  156,  402,  170,  401,  162,  400,
      169,  161,  163,  168,  173,  206,  178,  172,  180,  188,
      181,  171,  189,  194,  200,  176,  177,  182,  412,  184,
      185,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  190,  193,  201,  208,  202,  212,  214,
      399,  398,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  196,  196,  199,  210,  397,  396,
      395,  220,  197,  204,  204,  209,  191,  221,  222,  282,
      394,  393,  392,  391,  390,  283,  284,  389,  388,  387,

      386,  385,  206,  384,  383,  382,  381,  198,  198,  200,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,   63,   63,   63,   63,   63,  380,   63,   71,
      379,  378,  377,   71,   71,   71,   71,   75,   75,   75,
       75,   75,   75,   47,  376,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   94,  375,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   98,  374,   98,
      373,  372,  371,   98,   98,   98,   99,   99,  370,  369,
      368,   99,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  111,  111,  111,  111,  114,  114,

      114,  114,  114,  114,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  155,  367,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  186,  186,
      186,  186,  186,  187,  187,  187,  187,  187,  187,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,

      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  219,  218,  217,  215,  213,  203,  207,  203,

      203,  104,  192,  412,  183,  412,  179,  412,  412,  412,
      174,  412,  412,  412,  156,  167,  167,  166,  412,  412,
      412,  412,  156,  135,  152,  412,  412,  138,  135,  134,
      133,  132,  412,  412,  412,  412,  103,   64,   97,   97,
       97,   96,   93,   52,   91,   90,   89,   88,   82,   76,
       64,   46,   57,   57,   52,   51,   46,  412,    5,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412
    } ;

static yyconst short int yy_chk[1128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,  410,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   13,  409,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   47,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   19,   20,   19,   19,   47,   20,
       20,   21,   23,   23,   25,   25,   35,   38,   21,   21,
       21,   21,   67,   67,  407,   38,   35,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   50,
       49,   79,   50,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   27,   34,
       73,   73,   27,   49,   27,   27,   34,   27,   27,   31,
       31,   37,   63,   34,   37,   37,   63,   79,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       32,   58,   61,   58,   58,   78,   93,   32,   32,   68,
       61,   68,   68,  406,   68,   68,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   59,  404,
       59,   59,  110,  110,   65,  403,   65,   65,   78,   93,
       59,   62,   65,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   69,
       69,   69,   69,   72,   76,   72,   72,   77,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       74,   80,   81,   82,   83,   87,   84,   74,   85,   74,
       74,   88,   92,   94,  117,   92,  122,   89,   90,   91,
      100,   76,  100,  100,  101,   95,  101,  101,   95,  101,
      101,  103,  106,  111,  111,  118,  103,   77,  119,   80,
      106,  109,  123,  109,  109,  121,   94,  117,   92,  109,
      122,   83,  124,   82,   81,   84,   87,   85,   89,   90,
       91,   95,   88,  105,  105,  105,  105,  112,  120,  112,

      112,  115,  118,  115,  115,  116,  116,  126,  121,  123,
      142,  130,  128,  402,  129,  124,  143,  119,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  113,  113,  113,  113,  130,  126,  120,
      131,  142,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  128,  129,  135,  139,  143,  144,
      146,  135,  147,  148,  149,  151,  159,  158,  156,  160,
      162,  163,  167,  168,  164,  169,  178,  167,  171,  185,
      184,  176,  181,  182,  131,  401,  189,  208,  400,  214,

      198,  192,  208,  193,  214,  201,  209,  188,  212,  149,
      139,  194,  151,  144,  156,  399,  160,  398,  147,  397,
      159,  146,  148,  158,  164,  198,  171,  163,  176,  184,
      178,  162,  185,  189,  192,  168,  169,  178,  202,  181,
      182,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  186,  188,  193,  201,  194,  209,  212,
      396,  395,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  190,  196,  199,  206,  394,  393,
      392,  218,  190,  196,  199,  202,  186,  218,  218,  279,
      391,  390,  389,  388,  387,  279,  279,  386,  385,  384,

      383,  382,  206,  381,  380,  379,  378,  190,  196,  199,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  414,  414,  414,  414,  414,  377,  414,  415,
      376,  375,  374,  415,  415,  415,  415,  416,  416,  416,
      416,  416,  416,  417,  373,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  418,  372,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  419,  371,  419,
      370,  369,  368,  419,  419,  419,  420,  420,  367,  366,
      365,  420,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  422,  422,  422,  422,  423,  423,

      423,  423,  423,  423,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  425,  364,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  426,  426,
      426,  426,  426,  427,  427,  427,  427,  427,  427,  428,
      428,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,

      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      293,  292,  291,  290,  289,  288,  287,  286,  284,  283,
      282,  281,  280,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  217,  216,  215,  213,  211,  204,  200,  197,

      195,  191,  187,  180,  179,  177,  174,  173,  172,  170,
      166,  165,  161,  157,  155,  154,  153,  152,  150,  145,
      141,  140,  138,  136,  132,  127,  125,  108,  102,   99,
       98,   96,   86,   75,   71,   66,   60,   56,   55,   54,
       53,   51,   48,   44,   42,   41,   40,   39,   36,   33,
       26,   24,   18,   16,   12,   10,    8,    5,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "online.l"
#define INITIAL 0
#define STK 1

#line 5 "online.l"

#include<fstream>
#include<iostream>
#include<math.h>
#include<stdlib.h>
#include<cstdio>
#include<string.h>
#include<string>
using namespace std;

int line_count=1;
int error_count=0;
FILE *logout;
FILE *tokenout;
int global=0;
class SymbolInfo
{
private:
    string name;
    string type;

public:
    int flag=-1;
    SymbolInfo * next= NULL;
    string get_name(){return name;};
    string get_type(){return type;};
    void set_name(string str){name=str;};
    void set_type(string str){type=str;};
};


class scopeTable
{
   scopeTable * parent= NULL;
   public:

    SymbolInfo * r= NULL;
    int id= -1;
    //id++;
    int num;
    scopeTable * get_parent(){return parent;}
    void set_parent(scopeTable * s){parent=s;};

    scopeTable(int n)
    {
        r=new SymbolInfo[n];
        num=n;
    }

    int Hash(string k)
    {

         int i,j=0,l;
        char c;
        for(i=0;i<k.length();i++)
        {   c=k[i];
            j=j+c*pow(10,i);
            }
            int a=j;
    a += ~(a<<15);
    a ^=  (a>>10);
    a +=  (a<<3);
    a ^=  (a>>6);
    a += ~(a<<11);
    a ^=  (a>>16);
    a=a%num;
    return a;
    }

    SymbolInfo * lookup(string key)
    {
        int i,j=0,k;
        SymbolInfo * res=NULL;
        SymbolInfo * a=NULL;
        i=Hash(key);
        if(key == r[i].get_name())
            {
                res= &r[i];

            }
        else
        {
            if(r[i].next != NULL)
            {
                a=r[i].next;
                j++;
                while(a != NULL)
                {
                    if(a->get_name() == key)
                    {
                        res=a;
                        break;
                    }
                    else
                    {
                        a=a->next;
                        j++;
                    }
                }
            }
            else
            {
                //cout<<"Not found"<<endl;
                return res;
            }

        }
        //cout<<"Found in scopeTable #"<<id<<" at position "<<i<<","<<j<<endl;
        return res;
    }

    bool insert(string k,string t)
    {
        int index,cnt=0;

        SymbolInfo * skp;
        skp=lookup(k);
        if(skp != NULL)
        {
          //  cout<<"item already exist"<<endl;
            return false;
        }
        //cout<<k<<t<<endl;
        index = Hash(k);
        //cout<<index<<endl;
        if(r[index].flag == -1 )
        {
        r[index].set_name(k);
        r[index].set_type(t);
        r[index].flag = 3;
        }
        else if(r[index].flag != -1 && r[index].next == NULL)
        {
            SymbolInfo * r1=new SymbolInfo();

            r1->set_name(k);
            r1->set_type(t);
            r1->next=NULL;
            r[index].next=r1;
            cnt++;

        }

        else if(r[index].flag != -1 && r[index].next != NULL )
        {
           SymbolInfo * r1=new SymbolInfo();
           r1->set_name(k);
           r1->set_type(t);
           r1->next=r[index].next;
           r[index].next=r1;
            cnt++;
        }

        cout<<"Inserted in scopeTable #"<<id<<" at position "<<index<<","<<cnt<<endl;
        //print();
        return true;
    }

    void print()
    {
        SymbolInfo * q;
		
        cout<<"ScopeTable #"<<this->id<<endl;
        for(int i=0;i<num;i++)
        {
            cout<<i<<"-->  "<<"<"<<this->r[i].get_name()<<","<<this->r[i].get_type()<<"> ";
            q=this->r[i].next;
            while(q!= NULL)
            {
		
                cout<<"<"<<q->get_name()<<","<<q->get_type()<<"> ";
                q = q->next;
            }
            cout<<endl;
        }
    }

    bool Delete(string k)
    {
        SymbolInfo *sk =lookup(k);
        int j=0;
        if(sk == NULL){
           // cout<<"Unsuccessful deletion: item not found"<<endl;
            return false;
        }
        SymbolInfo * r2;
        SymbolInfo *r3;

        int in=Hash(k);

        if(r[in].get_name() == k && r[in].next == NULL)
        {
            r[in].flag = -1;
            r[in].set_name("");
            r[in].set_type("");

        }

        else if(r[in].get_name() == k && r[in].next != NULL)
        {
            r2=r[in].next;
            while(r2!= NULL)
            {
                r[in].set_name(r2->get_name());
                r[in].set_type(r2->get_type());
                r[in].next=r2->next;
                r2=r[in].next;
            }
        }

        else if(r[in].get_name() != k )
        {
            r2=r[in].next;
            j++;
            r3=&r[in];
            while(1)
            {
                if(r2->get_name() == k)
                    break;
                else{
                    r3=r2;
                    r2=r3->next;
                    j++;
                    }
            }
            if(r2->next == NULL)
            {
                r3->next = NULL;
            }
            else if(r2->next != NULL){

                r3->next=r2->next;

            }}

            //cout<<"deleted entry from scopeTable# "<<id<<" at position "<<in<<","<<j<<endl;
            return true;
            }

    ~scopeTable()
    {
        delete(r);
        delete(parent);
    }
            //end
};

class SymbolTable{

    scopeTable * current=NULL;
    int num;
public:
     int uid=0;
	SymbolTable()
{

		int n=10;
		num=10;
        //cout<<current<<endl;
        scopeTable * sc=new scopeTable(n);
        sc->id=uid;

        current=sc;
        sc=NULL;
        delete(sc);
        //cout<<current<<endl;
        //current->insert("hi","int");
        //current->print();

        uid++;


}
	
	 
    SymbolTable(int n)
    {	
        num=n;
        //cout<<current<<endl;
        scopeTable * sc=new scopeTable(n);
        sc->id=uid;

        current=sc;
        sc=NULL;
        delete(sc);
        //cout<<current<<endl;
        //current->insert("hi","int");
        //current->print();

        uid++;
    }

    scopeTable * get_current(){return current;};
    void set_current(scopeTable * s){current=s;};

    void enter_scope()
    {

        scopeTable * sc=new scopeTable(num);
        sc->id=uid;
        sc->set_parent(current);
        current=sc;
        sc=NULL;
        delete(sc);
        cout<<"New scope with id "<<uid<<" created"<<endl;
        uid++;

    }

    void exit_scope()
    {
        current = current->get_parent();
        if(current == NULL)
        {
            cout<<"exiting now"<<endl;
            exit(0);

        }

    }

    bool insert(string name,string type)
    {
        if(current !=NULL)
        {
            return current->insert(name,type);

        }
        else
        {
            cout<<"Open a scope first"<<endl;
            return false;
        }
    }

    bool Remove(string name)
    {
       return current->Delete(name);
    }

    void print_current()
    {
        current->print();
    }

    SymbolInfo * lookup(string k)
    {
        SymbolInfo * res;
        scopeTable * ex;
        res = current->lookup(k);

        ex=current->get_parent();
        while(res == NULL && ex != NULL )
        {
            res = ex->lookup(k);
            if(res != NULL){
                    //ex=NULL;
                return res;}
            ex=ex->get_parent();
        }
        //ex = NULL;
        return res;
    }

    void print_all()
    {
        current->print();
        //cout<<endl;
        scopeTable * ex=current->get_parent();
        while(ex !=NULL)
              {
                  ex->print();
                  cout<<endl;
                  ex=ex->get_parent();
              }
              //ex=NULL;
    }
};

SymbolTable st(10);

#line 1178 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 400 "online.l"


#line 1332 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 413 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1059 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 402 "online.l"
{line_count++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 404 "online.l"
{
			fprintf(tokenout,"<IF>");
			fprintf(logout,"Line no %d: TOKEN <IF> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 408 "online.l"
{
			fprintf(tokenout,"<ELSE>");
			fprintf(logout,"Line no %d: TOKEN <ELSE> Lexeme %s found\n",line_count,yytext);
		}		
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 414 "online.l"
{
			fprintf(tokenout,"<FOR>");
			fprintf(logout,"Line no %d: TOKEN <FOR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 420 "online.l"
{
			fprintf(tokenout,"<WHILE>");
			fprintf(logout,"Line no %d: TOKEN <WHILE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 425 "online.l"
{
			fprintf(tokenout,"<DO>");
			fprintf(logout,"Line no %d: TOKEN <DO> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 429 "online.l"
{
			fprintf(tokenout,"<BREAK>");
			fprintf(logout,"Line no %d: TOKEN <BREAK> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 434 "online.l"
{
			fprintf(tokenout,"<INT>");
			fprintf(logout,"Line no %d: TOKEN <INT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 438 "online.l"
{
			fprintf(tokenout,"<CHAR>");
			fprintf(logout,"Line no %d: TOKEN <CHAR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 442 "online.l"
{
			fprintf(tokenout,"<FLOAT>");
			fprintf(logout,"Line no %d: TOKEN <FLOAT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 446 "online.l"
{
			fprintf(tokenout,"<DOUBLE>");
			fprintf(logout,"Line no %d: TOKEN <DOUBLE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 451 "online.l"
{
			fprintf(tokenout,"<VOID>");
			fprintf(logout,"Line no %d: TOKEN <VOID> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 455 "online.l"
{
			fprintf(tokenout,"<RETURN>");
			fprintf(logout,"Line no %d: TOKEN <RETURN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 460 "online.l"
{
			fprintf(tokenout,"<SWITCH>");
			fprintf(logout,"Line no %d: TOKEN <SWITCH> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 464 "online.l"
{
			fprintf(tokenout,"<CASE>");
			fprintf(logout,"Line no %d: TOKEN <CASE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 468 "online.l"
{
			fprintf(tokenout,"<DEFAULT>");
			fprintf(logout,"Line no %d: TOKEN <DEFAULT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 472 "online.l"
{
			fprintf(tokenout,"<CONTINUE>");
			fprintf(logout,"Line no %d: TOKEN <CONTINUE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 478 "online.l"
{
				fprintf(tokenout,"<CONST_INT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_INT> Lexeme %s found\n",line_count,yytext);
				st.insert(yytext,"CONST_INT");
				st.print_all();

		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 485 "online.l"
{
				fprintf(tokenout,"<CONST_FLOAT,%s>",yytext);
				fprintf(logout,"Line no %d: TOKEN <CONST_FLOAT> Lexeme %s found\n\n",line_count,yytext);
				st.insert(yytext,"CONST_FLOAT");
				st.print_all();				
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 491 "online.l"
{
				
			
				fprintf(tokenout,"<CONST_CHAR,%c>",yytext[1]);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,yytext[1]);
				st.insert(yytext,"CONST_CHAR");
				st.print_all();
				
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 500 "online.l"
{
				char c;
				
				if(yytext[2] == 'n')
				{
				c=10;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",10);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,10);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 't')
				{
				c=9;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",9);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,9);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == '\\')
				{
				c=92;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",92);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,92);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == '\'')
				{
				c=39;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",39);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,39);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'a')
				{
				c=7;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",7);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,7);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'a')
				{
				c=7;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",7);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,7);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'f')
				{
				c=12;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",12);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,12);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'r')
				{
				c=13;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",13);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,13);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'b')
				{
				c=8;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",8);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,8);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == 'v')
				{
				c=11;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",11);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,11);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				else if(yytext[2] == '0')
				{
				c=0;
				string str(1,c);
				fprintf(tokenout,"<CONST_CHAR,%c>",0);
				fprintf(logout,"Line no %d: TOKEN <CONST_CHAR> Lexeme %c found\n\n",line_count,0);
				st.insert(str,"CONST_CHAR");	
				st.print_all();
						
				}
				
				
			}				
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 626 "online.l"
{
			fprintf(tokenout,"<ADDOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ADDOP> Lexeme %s found\n",line_count,yytext);		
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 631 "online.l"
{
			fprintf(tokenout,"<MULOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <MULOP> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 636 "online.l"
{
			fprintf(tokenout,"<INCOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <INCOP> Lexeme %s found\n",line_count,yytext);
		}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 641 "online.l"
{
			fprintf(tokenout,"<RELOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RELOP> Lexeme %s found\n",line_count,yytext);	
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 646 "online.l"
{
			fprintf(tokenout,"<ASSIGNOP,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ASSIGNOP> Lexeme %s found\n",line_count,yytext);
			
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 652 "online.l"

	YY_BREAK

case 28:
YY_RULE_SETUP
#line 654 "online.l"

	YY_BREAK
case 29:
YY_RULE_SETUP
#line 655 "online.l"

	YY_BREAK

case 30:
YY_RULE_SETUP
#line 659 "online.l"

	YY_BREAK

case 31:
YY_RULE_SETUP
#line 661 "online.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 662 "online.l"

	YY_BREAK

case 33:
YY_RULE_SETUP
#line 666 "online.l"

	YY_BREAK

case 34:
YY_RULE_SETUP
#line 668 "online.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 669 "online.l"

	YY_BREAK

case 36:
YY_RULE_SETUP
#line 672 "online.l"
{
			fprintf(tokenout,"<LPAREN,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LPAREN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 677 "online.l"
{
			fprintf(tokenout,"<RPAREN,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RPAREN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 681 "online.l"
{
			fprintf(tokenout,"<LCURL,%s>",yytext);
			global=1;
			fprintf(logout,"Line no %d: TOKEN <LCURL> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 686 "online.l"
{
			fprintf(tokenout,"<RCURL,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RCURL> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 691 "online.l"
{
			fprintf(tokenout,"<LTHIRD,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <LTHIRD> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 695 "online.l"
{
			fprintf(tokenout,"<RTHIRD,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <RTHIRD> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 699 "online.l"
{
			fprintf(tokenout,"<COMMA,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <COMMA> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 703 "online.l"
{
			fprintf(tokenout,"<SEMICOLON,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <SEMICOLON> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 709 "online.l"
{
			
			fprintf(tokenout,"<ID,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <ID> Lexeme %s found\n",line_count,yytext);
			st.insert(yytext,"ID");
			st.print_all();
		
		}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 717 "online.l"
{	
			string str(yytext);
			
			str.erase(0,1);
			str.erase(str.length()-1,1);
			
			
			int in=str.find("\\n");
			if(in>-1 && in<str.length())
			{
				char c=10;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s\n",yytext);
			}
			 in=str.find("\\t");
			if(in>-1 && in<str.length())
			{
				char c=9;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s\n",yytext);
			}
			
			in=str.find("\\b");
			if(in>-1 && in<str.length())
			{
				char c=8;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\a");
			if(in>-1 && in<str.length())
			{
				char c=7;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\v");
			if(in>-1 && in<str.length())
			{
				char c=11;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\f");
			if(in>-1 && in<str.length())
			{
				char c=12;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\0");
			if(in>-1 && in<str.length())
			{
				char c=0;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\r");
			if(in>-1 && in<str.length())
			{
				char c=13;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\'");
			if(in>-1 && in<str.length())
			{
				char c=39;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\");
			if(in>-1 && in<str.length()-1)
			{
				char c=92;
				string str2(1,c);
				str.replace(in,1,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
				
			}
			//cout<<str<<endl;
			fprintf(tokenout,"<STRING,%s>",yytext);
			fprintf(logout,"Line no %d: TOKEN <STRING> Lexeme %s found\n",line_count,yytext);
			
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 831 "online.l"
{
		int multi=0,init,k;
		init=line_count;
		string str3(yytext);
		//cout<<"MS:"<<yytext<<endl;
		str3.erase(0,1);
		str3.erase(str3.length()-1,1);
		
		int in=str3.find("\n");
		if(in>-1 && in<str3.length()){
		multi=1;
		}
		k=in;
		if(multi ==1){
		while(k>-1 && k<str3.length())
		{
		k=str3.find("\n",k+1);
		line_count++;
		}
		
		strcpy(yytext, str3.c_str());
		string str(yytext);
			
		int in=str.find("\\n");
			if(in>-1 && in<str.length())
			{
				char c=10;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s\n",yytext);
			}
			 in=str.find("\\t");
			if(in>-1 && in<str.length())
			{
				char c=9;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s\n",yytext);
			}
			
			in=str.find("\\b");
			if(in>-1 && in<str.length())
			{
				char c=8;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\a");
			if(in>-1 && in<str.length())
			{
				char c=7;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\v");
			if(in>-1 && in<str.length())
			{
				char c=11;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\f");
			if(in>-1 && in<str.length())
			{
				char c=12;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\0");
			if(in>-1 && in<str.length())
			{
				char c=0;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\r");
			if(in>-1 && in<str.length())
			{
				char c=13;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\'");
			if(in>-1 && in<str.length())
			{
				char c=39;
				string str2(1,c);
				str.replace(in,2,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
			}
			
			in=str.find("\\");
			if(in>-1 && in<str.length()-1)
			{
				char c=92;
				string str2(1,c);
				str.replace(in,1,str2);
				strcpy(yytext, str.c_str());
			//printf("string: %s",yytext);
				
			}
		fprintf(tokenout,"<STRING,%s>",yytext);
		fprintf(logout,"Line no %d: TOKEN <STRING> Lexeme %s found\n",init,yytext);
}
} 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 957 "online.l"
{
		int multi=0,k,init=line_count;
		string str3(yytext);
		//cout<<yytext<<endl;
		str3.erase(0,2);
		int in=str3.find("\n");
		if(in>-1 && in<str3.length()){
		multi=1;
		}
		k=in;
		if(multi ==1){
		while(k>-1 && k<str3.length())
		{
		k=str3.find("\n",k+1);
		line_count++;
		}}
		
		strcpy(yytext, str3.c_str());
		fprintf(logout,"Line no %d: <COMMENT>  %s found\n",init,yytext);
 
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 979 "online.l"
{
		int multi=0,k,init=line_count;
		string str3(yytext);
		//cout<<"lkkkk:"<<yytext<<endl;
		str3.erase(0,2);
		str3.erase(str3.length()-2,2);
		int in=str3.find("\n");
		if(in>-1 && in<str3.length()){
		multi=1;
		}
		k=in;
		if(multi ==1){
		while(k>-1 && k<str3.length())
		{
		k=str3.find("\n",k+1);
		line_count++;
		}}
		
		strcpy(yytext, str3.c_str());
		fprintf(logout,"Line no %d:<COMMENT>  %s found\n",init,yytext);

}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 1002 "online.l"
{

		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		if(global==0){
		fprintf(logout,"Line no %d: TOKEN <Header File> %s included\n",line_count,yytext);}
		else
		{
		fprintf(logout,"ERROR: Line no %d: <ERROR> Global scope ERROR %s found\n",line_count,yytext);
		error_count++;
		}

}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 1020 "online.l"
{
		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> Invalid Header File %s found\n",line_count,yytext);
		error_count++;


}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 1034 "online.l"
{
		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> Invalid Header File %s found\n",line_count,yytext);
		error_count++;


}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 1048 "online.l"
{
		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> Invalid Header File %s found\n",line_count,yytext);
		error_count++;


}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 1062 "online.l"
{
		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> Invalid Header File %s found\n",line_count,yytext);
		error_count++;


}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 1076 "online.l"
{
		string str(yytext);
		int in=str.find("<");
		int en=str.find(">");
		cout<<en-in-1<<endl;
		str.erase(0,in);
		//str.erase(en+1,str.length()-en-1);
		strcpy(yytext,str.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> Invalid Header File %s found\n",line_count,yytext);
		error_count++;


}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 1089 "online.l"
{
		fprintf(logout,"ERROR: Line no %d: <ERROR> TOO MANY DECIMAL POINT %s found\n",line_count,yytext);	
		error_count++;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 1094 "online.l"
{
		fprintf(logout,"ERROR: Line no %d: <ERROR> ILL FORMED NUMBER %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 1099 "online.l"
{
		fprintf(logout,"ERROR: Line no %d: <ERROR> INVALID NUMERIC CONSTANT/IDENTIFIER %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 1104 "online.l"
{
		fprintf(logout,"ERROR: Line no %d: <ERROR> MULTIPLE CHARACTER CONSTANT %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 1108 "online.l"
{
		fprintf(logout,"ERROR: Line no %d: <ERROR> INCOMPLETE CHARACTER %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 1113 "online.l"
{
		int multi=0,k,init=line_count;
		string str3(yytext);
		//cout<<yytext<<endl;
		str3.erase(0,1);
		int in=str3.find("\n");
		if(in>-1 && in<str3.length()){
		multi=1;
		}
		k=in;
		if(multi ==1){
		while(k>-1 && k<str3.length())
		{
		k=str3.find("\n",k+1);
		line_count++;
		}}
		
		strcpy(yytext, str3.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> UNFINISHED STRING %s found\n",init,yytext);
		error_count++;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 1135 "online.l"
{
		int multi=0,k,init=line_count;
		string str3(yytext);
		cout<<yytext<<endl;
		str3.erase(0,2);
		int in=str3.find("\n");
		if(in>-1 && in<str3.length()){
		multi=1;
		}
		k=in;
		if(multi ==1){
		while(k>-1 && k<str3.length())
		{
		k=str3.find("\n",k+1);
		//cout<<"done"<<endl;
		line_count++;
		}}
		
		strcpy(yytext, str3.c_str());
		fprintf(logout,"ERROR: Line no %d: <ERROR> UNFINISHED COMMENT %s found\n",init,yytext);
		error_count++;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 1158 "online.l"
{
	fprintf(logout,"ERROR: Line no %d: <ERROR> UNTERMINATED CHARACTER %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 1162 "online.l"
{
	fprintf(logout,"ERROR: Line no %d: <ERROR> EMPTY CHARACTER %s found\n",line_count,yytext);
		error_count++;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 1166 "online.l"
ECHO;
	YY_BREAK
#line 2404 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(STK):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 413 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 413 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 412);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1166 "online.l"


int main(int argc,char *argv[]){
	
	SymbolTable st(10);
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout= fopen("1605050_log.txt","w+");
	tokenout= fopen("1605050_token.txt","w+");

	yyin= fin;
	yylex();
	
	fprintf(logout,"TOTAL ERROR: %d\n",error_count);
	fprintf(logout,"TOTAL LINES: %d",line_count);
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}